(()=>{
  const panel=$('#soundColorsPanel'),pads=$$('.sc-pad'),names={ro:['Roșu','Albastru','Verde','Galben'],en:['Red','Blue','Green','Yellow']},freqs=[261.6,329.6,392,523.3];
  let sequence=[],step=0,busy=true,ctx=null,hits=0,presses=0,best=+(localStorage.sgSoundColorsBest||0);
  const wait=ms=>new Promise(r=>setTimeout(r,ms)),speed=()=>+$('#scSpeed').value,setPads=on=>pads.forEach(p=>p.disabled=!on);
  function copy(){let en=state.lang==='en',n=names[state.lang],mode=en?'Sounds & Colors':'Sunete și Culori';$('#scTitle').textContent=mode;$('#scSpeedLabel').textContent=en?'Speed':'Viteză';$('#scSoundLabel').textContent=en?'Sound on':'Sunet activat';$('#scHint').textContent=en?'Use keys 1–4, Tab + Enter/Space, or touch. There is no time limit.':'Folosește tastele 1–4, Tab + Enter/Space sau atingerea. Nu există limită de timp.';$('#scGrid').setAttribute('aria-label',en?'Game buttons':'Butoanele jocului');pads.forEach((p,i)=>{p.querySelector('b').textContent=n[i];p.setAttribute('aria-label',(i+1)+'. '+n[i])});$('#scSpeed').options[0].textContent=en?'Slow':'Lentă';$('#scSpeed').options[1].textContent=en?'Normal':'Normală';$('#scSpeed').options[2].textContent=en?'Fast':'Rapidă';let o=$('#gameType option[value="soundColors"]'),t=$('#teacherMode option[value="soundColors"]');if(o)o.textContent=mode;if(t)t.textContent=mode;score()}
  function say(ro,en){$('#scStatus').textContent=state.lang==='en'?en:ro}
  function score(){$('#scScore').textContent=(state.lang==='en'?'Level: ':'Nivel: ')+sequence.length+' • '+(state.lang==='en'?'Best: ':'Record: ')+best}
  function tone(i){if(!$('#scSound').checked)return;ctx=ctx||new (window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();let o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=freqs[i];g.gain.setValueAtTime(.0001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.28,ctx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.38);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.4)}
  async function flash(i){pads[i].classList.add('lit');tone(i);await wait(speed());pads[i].classList.remove('lit');await wait(Math.round(speed()/2))}
  async function play(){busy=true;setPads(false);say('Ascultă și privește secvența…','Listen and watch the sequence…');await wait(550);for(const i of sequence)await flash(i);step=0;busy=false;setPads(true);say('Rândul tău: repetă secvența.','Your turn: repeat the sequence.');pads[0].focus()}
  function next(){sequence.push(Math.floor(Math.random()*4));score();play()}
  function saveSession(){let reached=Math.max(0,sequence.length-1),points=reached*100;best=Math.max(best,reached);localStorage.sgSoundColorsBest=best;profile.games++;profile.xp+=points;profile.flowers+=reached;profile.answers+=presses;profile.hits+=hits;profile.history.unshift({date:new Date().toLocaleDateString(state.lang==='en'?'en-GB':'ro-RO'),mode:state.lang==='en'?'Sounds & Colors':'Sunete și Culori',score:points});profile.history=profile.history.slice(0,20);saveProfile();renderProfile();score()}
  async function press(i){if(busy||!sequence.length)return;pads[i].classList.add('lit');tone(i);setTimeout(()=>pads[i].classList.remove('lit'),220);presses++;if(i===sequence[step]){hits++;step++;if(step===sequence.length){busy=true;setPads(false);best=Math.max(best,sequence.length);localStorage.sgSoundColorsBest=best;score();say('Corect! Nivel reușit.','Correct! Level completed.');await wait(850);next()}}else{busy=true;setPads(false);saveSession();say('Greșit. Culoarea corectă era '+names.ro[sequence[step]]+'. Apasă Start pentru a reîncepe.','Not quite. The correct colour was '+names.en[sequence[step]]+'. Press Start to try again.');$('#scStart').textContent='Start';$('#scStart').focus()}}
  function start(){sequence=[];step=0;hits=0;presses=0;busy=false;$('#scStart').textContent=state.lang==='en'?'Restart':'Repornește';say('Jocul începe!','The game begins!');next()}
  pads.forEach((p,i)=>p.onclick=()=>press(i));$('#scStart').onclick=start;$('#scClose').onclick=()=>{busy=true;setPads(false);panel.close()};$('#scSpeed').onchange=()=>localStorage.sgSoundColorsSpeed=$('#scSpeed').value;$('#scSound').onchange=()=>localStorage.sgSoundColorsSound=$('#scSound').checked;
  $('#scSpeed').value=localStorage.sgSoundColorsSpeed||'450';$('#scSound').checked=localStorage.sgSoundColorsSound!=='false';
  const prior=translateExtended;translateExtended=function(){prior();copy();document.title=state.lang==='en'?'Signal Garden 4.1 — Accessible Game':'Signal Garden 4.1 — Joc accesibil';let cp=$$('#certificate p');if(cp.length)cp[cp.length-1].textContent=(state.lang==='en'?'6 September 2026':'6 septembrie 2026')+' • Signal Garden 4.1'};
  const normalStart=$('#startBtn').onclick;$('#startBtn').onclick=()=>{if($('#gameType').value!=='soundColors')return normalStart();copy();say('Apasă Start pentru a începe.','Press Start to begin.');score();panel.showModal();$('#scStart').focus()};
  document.addEventListener('keydown',e=>{if(!panel.open||busy)return;let i=Number(e.key)-1;if(i>=0&&i<4){e.preventDefault();press(i)}},true);addEventListener('load',copy);copy();
})();
